<?php
require_once 'vendor/autoload.php';
$faker = Faker\Factory::create('en_US');
for ($i = 0; $i < 3; $i++) {

   $address = $faker->streetAddress;
   $cityx = $faker->cityPrefix;
   $state = $faker->state;
   $zip = $faker ->postcode;
   $company = $faker->company;
   $country = $faker->country;
}

$citiesAndStates = [
    ["city" => "New York", "state" => "New York"],
    ["city" => "Los Angeles", "state" => "California"],
    ["city" => "Chicago", "state" => "Illinois"],
    ["city" => "Houston", "state" => "Texas"],
    ["city" => "Phoenix", "state" => "Arizona"],
    ["city" => "Philadelphia", "state" => "Pennsylvania"],
    ["city" => "San Antonio", "state" => "Texas"],
    ["city" => "San Diego", "state" => "California"],
    ["city" => "Dallas", "state" => "Texas"],
    ["city" => "San Jose", "state" => "California"],
    ["city" => "Austin", "state" => "Texas"],
    ["city" => "Jacksonville", "state" => "Florida"],
    ["city" => "Fort Worth", "state" => "Texas"],
    ["city" => "Columbus", "state" => "Ohio"],
    ["city" => "San Francisco", "state" => "California"],
    ["city" => "Charlotte", "state" => "North Carolina"],
    ["city" => "Indianapolis", "state" => "Indiana"],
    ["city" => "Seattle", "state" => "Washington"],
    ["city" => "Denver", "state" => "Colorado"],
    ["city" => "Washington", "state" => "District of Columbia"],
    ["city" => "Boston", "state" => "Massachusetts"],
    ["city" => "El Paso", "state" => "Texas"],
    ["city" => "Detroit", "state" => "Michigan"],
    ["city" => "Nashville", "state" => "Tennessee"],
    ["city" => "Portland", "state" => "Oregon"],
    ["city" => "Memphis", "state" => "Tennessee"],
    ["city" => "Oklahoma City", "state" => "Oklahoma"],
    ["city" => "Las Vegas", "state" => "Nevada"],
    ["city" => "Louisville", "state" => "Kentucky"],
    ["city" => "Baltimore", "state" => "Maryland"],
    ["city" => "Milwaukee", "state" => "Wisconsin"],
    ["city" => "Albuquerque", "state" => "New Mexico"],
    ["city" => "Tucson", "state" => "Arizona"],
    ["city" => "Fresno", "state" => "California"],
    ["city" => "Sacramento", "state" => "California"],
    ["city" => "Mesa", "state" => "Arizona"],
    ["city" => "Kansas City", "state" => "Missouri"],
    ["city" => "Atlanta", "state" => "Georgia"],
    ["city" => "Long Beach", "state" => "California"],
    ["city" => "Colorado Springs", "state" => "Colorado"],
    ["city" => "Miami", "state" => "Florida"],
    ["city" => "Raleigh", "state" => "North Carolina"],
    ["city" => "Omaha", "state" => "Nebraska"],
    ["city" => "Minneapolis", "state" => "Minnesota"],
    ["city" => "New Orleans", "state" => "Louisiana"],
    ["city" => "Wichita", "state" => "Kansas"],
    ["city" => "Cleveland", "state" => "Ohio"],
    ["city" => "Tulsa", "state" => "Oklahoma"],
    ["city" => "Arlington", "state" => "Texas"],
    ["city" => "Newark", "state" => "New Jersey"],
    ["city" => "Tampa", "state" => "Florida"],
    ["city" => "Aurora", "state" => "Colorado"],
    ["city" => "Anaheim", "state" => "California"],
    ["city" => "Santa Ana", "state" => "California"],
    ["city" => "St. Louis", "state" => "Missouri"],
    ["city" => "Pittsburgh", "state" => "Pennsylvania"],
    ["city" => "Corpus Christi", "state" => "Texas"],
    ["city" => "Riverside", "state" => "California"],
    ["city" => "Cincinnati", "state" => "Ohio"],
    ["city" => "Lexington", "state" => "Kentucky"],
    ["city" => "Anchorage", "state" => "Alaska"],
    ["city" => "Stockton", "state" => "California"],
    ["city" => "Toledo", "state" => "Ohio"],
    ["city" => "St. Paul", "state" => "Minnesota"],
    ["city" => "New Haven", "state" => "Connecticut"],
    ["city" => "Greensboro", "state" => "North Carolina"],
    ["city" => "Jersey City", "state" => "New Jersey"],
    ["city" => "St. Petersburg", "state" => "Florida"],
    ["city" => "Chula Vista", "state" => "California"],
    ["city" => "Norfolk", "state" => "Virginia"],
    ["city" => "Orlando", "state" => "Florida"],
    ["city" => "Chandler", "state" => "Arizona"],
    ["city" => "Laredo", "state" => "Texas"],
    ["city" => "Madison", "state" => "Wisconsin"],
    ["city" => "Winston-Salem", "state" => "North Carolina"],
    ["city" => "Lubbock", "state" => "Texas"],
    ["city" => "Baton Rouge", "state" => "Louisiana"],
    ["city" => "Durham", "state" => "North Carolina"],
    ["city" => "Garland", "state" => "Texas"],
    ["city" => "Glendale", "state" => "Arizona"],
    ["city" => "Reno", "state" => "Nevada"],
    ["city" => "Hialeah", "state" => "Florida"],
    ["city" => "Chesapeake", "state" => "Virginia"],
    ["city" => "Scottsdale", "state" => "Arizona"],
    ["city" => "North Las Vegas", "state" => "Nevada"],
    ["city" => "Irvine", "state" => "California"],
    ["city" => "Gilbert", "state" => "Arizona"],
    ["city" => "San Bernardino", "state" => "California"],
    ["city" => "Columbia", "state" => "South Carolina"],
    ["city" => "Roseville", "state" => "California"],
    ["city" => "Denton", "state" => "Texas"],
    ["city" => "Carlsbad", "state" => "California"],
    ["city" => "Arvada", "state" => "Colorado"],
    ["city" => "Provo", "state" => "Utah"],
    ["city" => "Peoria", "state" => "Arizona"],
    ["city" => "Abilene", "state" => "Texas"],
    ["city" => "El Monte", "state" => "California"],
    ["city" => "Round Rock", "state" => "Texas"],
    ["city" => "Gainesville", "state" => "Florida"],
    ["city" => "Clearwater", "state" => "Florida"],
    ["city" => "Waterbury", "state" => "Connecticut"],
    ["city" => "Centennial", "state" => "Colorado"],
    ["city" => "Miami Gardens", "state" => "Florida"],
    ["city" => "College Station", "state" => "Texas"],
    ["city" => "West Valley City", "state" => "Utah"],
    ["city" => "South Bend", "state" => "Indiana"],
    ["city" => "Vancouver", "state" => "Washington"],
    ["city" => "Miami Beach", "state" => "Florida"],
    ["city" => "Boulder", "state" => "Colorado"],
    ["city" => "Daly City", "state" => "California"],
    ["city" => "Broken Arrow", "state" => "Oklahoma"],
    ["city" => "San Mateo", "state" => "California"],
    ["city" => "Green Bay", "state" => "Wisconsin"],
    ["city" => "Pueblo", "state" => "Colorado"],
    ["city" => "Norwalk", "state" => "California"],
    ["city" => "Sandy Springs", "state" => "Georgia"],
    ["city" => "Everett", "state" => "Washington"],
    ["city" => "Wichita Falls", "state" => "Texas"],
    ["city" => "La Mesa", "state" => "California"],
    ["city" => "Davenport", "state" => "Iowa"],
    ["city" => "Palm Bay", "state" => "Florida"],
    ["city" => "Costa Mesa", "state" => "California"],
    ["city" => "Downey", "state" => "California"],
    ["city" => "Carrollton", "state" => "Texas"],
    ["city" => "North Charleston", "state" => "South Carolina"],
    ["city" => "Mount Pleasant", "state" => "South Carolina"],
    ["city" => "Sparks", "state" => "Nevada"],
    ["city" => "Alhambra", "state" => "California"],
    ["city" => "Cape Coral", "state" => "Florida"],
    ["city" => "Portsmouth", "state" => "Virginia"],
    ["city" => "Lorain", "state" => "Ohio"],
    ["city" => "Lynn", "state" => "Massachusetts"],
    ["city" => "Redmond", "state" => "Washington"],
    ["city" => "Lake Charles", "state" => "Louisiana"],
    ["city" => "Greenville", "state" => "South Carolina"],
    ["city" => "Plymouth", "state" => "Minnesota"],
    ["city" => "Broomfield", "state" => "Colorado"],
    ["city" => "Bossier City", "state" => "Louisiana"],
    ["city" => "Miami", "state" => "Florida"],
    ["city" => "Lawrence", "state" => "Kansas"],
    ["city" => "Oshkosh", "state" => "Wisconsin"],
    ["city" => "Cicero", "state" => "Illinois"],
    ["city" => "Euless", "state" => "Texas"],
    ["city" => "Caldwell", "state" => "Idaho"],
    ["city" => "Beaumont", "state" => "Texas"],
    ["city" => "Lake Forest", "state" => "California"],
    ["city" => "Pawtucket", "state" => "Rhode Island"],
    ["city" => "Blacksburg", "state" => "Virginia"],
    ["city" => "St. Clair Shores", "state" => "Michigan"],
    ["city" => "Largo", "state" => "Florida"],
    ["city" => "Bend", "state" => "Oregon"],
    ["city" => "Tulare", "state" => "California"],
    ["city" => "Trenton", "state" => "New Jersey"],
    ["city" => "Brea", "state" => "California"],
    ["city" => "Saginaw", "state" => "Michigan"],
    ["city" => "Marietta", "state" => "Georgia"],
    ["city" => "Bowie", "state" => "Maryland"],
    ["city" => "Moline", "state" => "Illinois"],
    ["city" => "San Rafael", "state" => "California"],
    ["city" => "Chicopee", "state" => "Massachusetts"],
    ["city" => "Rock Hill", "state" => "South Carolina"],
    ["city" => "Mount Vernon", "state" => "New York"],
    ["city" => "La Quinta", "state" => "California"],
    ["city" => "Kalispell", "state" => "Montana"],
    ["city" => "Phenix City", "state" => "Alabama"],
    ["city" => "Haltom City", "state" => "Texas"],
    ["city" => "Dublin", "state" => "Ohio"],
    ["city" => "Carson", "state" => "California"],
    ["city" => "Bell Gardens", "state" => "California"],
    ["city" => "Parkersburg", "state" => "West Virginia"],
    ["city" => "Freeport", "state" => "Illinois"],
    ["city" => "Hobbs", "state" => "New Mexico"],
    ["city" => "Lancaster", "state" => "Texas"],
    ["city" => "Tustin", "state" => "California"],
    ["city" => "Mankato", "state" => "Minnesota"],
    ["city" => "Glendora", "state" => "California"],
    ["city" => "Norwich", "state" => "Connecticut"],
    ["city" => "San Jacinto", "state" => "California"],
    ["city" => "Malden", "state" => "Massachusetts"],
    ["city" => "Harlingen", "state" => "Texas"],
    ["city" => "Harrisonburg", "state" => "Virginia"],
    ["city" => "Cutler Bay", "state" => "Florida"],
    ["city" => "South San Francisco", "state" => "California"],
    ["city" => "Crystal Lake", "state" => "Illinois"],
    ["city" => "La Crosse", "state" => "Wisconsin"],
    ["city" => "Lompoc", "state" => "California"],
    ["city" => "Shelton", "state" => "Connecticut"],
    ["city" => "Moline", "state" => "Illinois"],
    ["city" => "Carrollton", "state" => "Texas"],
    ["city" => "Bethlehem", "state" => "Pennsylvania"],
    ["city" => "Owensboro", "state" => "Kentucky"],
    ["city" => "Carol Stream", "state" => "Illinois"],
    ["city" => "Lompoc", "state" => "California"],
    ["city" => "Ormond Beach", "state" => "Florida"],
    ["city" => "New Brunswick", "state" => "New Jersey"],
    ["city" => "Minnetonka", "state" => "Minnesota"],
    ["city" => "Owensboro", "state" => "Kentucky"],
    ["city" => "Lincoln Park", "state" => "Michigan"],
    ["city" => "La Mesa", "state" => "California"],
    ["city" => "Mankato", "state" => "Minnesota"],
    ["city" => "Eagan", "state" => "Minnesota"],
    ["city" => "Calexico", "state" => "California"],
    ["city" => "Muskogee", "state" => "Oklahoma"],
    ["city" => "DeSoto", "state" => "Texas"],
    ["city" => "Cleveland Heights", "state" => "Ohio"],
    ["city" => "Elkhart", "state" => "Indiana"],
    ["city" => "Marana", "state" => "Arizona"],
    ["city" => "Sayreville", "state" => "New Jersey"],
    ["city" => "Blaine", "state" => "Minnesota"],
    ["city" => "Cleveland Heights", "state" => "Ohio"],
    ["city" => "Bloomington", "state" => "Minnesota"],
    ["city" => "Shelton", "state" => "Connecticut"],
    ["city" => "Aliso Viejo", "state" => "California"],
    ["city" => "San Jacinto", "state" => "California"],
    ["city" => "Redmond", "state" => "Washington"],
    ["city" => "Lancaster", "state" => "Ohio"],
    ["city" => "La Crosse", "state" => "Wisconsin"],
    ["city" => "La Crosse", "state" => "Wisconsin"],
    ["city" => "Grand Forks", "state" => "North Dakota"],
    ["city" => "Gulfport", "state" => "Mississippi"],
    ["city" => "Haltom City", "state" => "Texas"],
    ["city" => "San Jacinto", "state" => "California"],
    ["city" => "Calexico", "state" => "California"],
    ["city" => "Lompoc", "state" => "California"],
    ["city" => "Muskogee", "state" => "Oklahoma"],
    ["city" => "Cleveland Heights", "state" => "Ohio"],
    ["city" => "Sayreville", "state" => "New Jersey"],
    ["city" => "Blaine", "state" => "Minnesota"],
    ["city" => "Cleveland Heights", "state" => "Ohio"],
    ["city" => "Bloomington", "state" => "Minnesota"],
    ["city" => "Shelton", "state" => "Connecticut"],
    ["city" => "Aliso Viejo", "state" => "California"],
    ["city" => "Redmond", "state" => "Washington"],
    ["city" => "Lancaster", "state" => "Ohio"],
    ["city" => "La Crosse", "state" => "Wisconsin"],
    ["city" => "Grand Forks", "state" => "North Dakota"],
    ["city" => "Gulfport", "state" => "Mississippi"],
    ["city" => "Haltom City", "state" => "Texas"],
    ["city" => "Cleveland Heights", "state" => "Ohio"],
    ["city" => "Bloomington", "state" => "Minnesota"],
    ["city" => "Shelton", "state" => "Connecticut"],
    ["city" => "Aliso Viejo", "state" => "California"],
    ["city" => "Redmond", "state" => "Washington"],
    ["city" => "Lancaster", "state" => "Ohio"],
    ["city" => "La Crosse", "state" => "Wisconsin"],
    ["city" => "Grand Forks", "state" => "North Dakota"],
    ["city" => "Gulfport", "state" => "Mississippi"],
    ["city" => "Haltom City", "state" => "Texas"],
    ["city" => "Cleveland Heights", "state" => "Ohio"],
    ["city" => "Bloomington", "state" => "Minnesota"],
];

$city = "{$cityx}";

$matchFound = false;
$matchingState = "";

foreach ($citiesAndStates as $cityAndState) {
    if ($cityAndState["city"] == $city) {
        $matchFound = true;
        $matchingState = $cityAndState["state"];
        break;
    }
}

if ($matchFound) {
    echo "Match found for city: " . $city . " and state: " . $matchingState;
} else {
    echo "No match found for city: " . $city;
}